spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://arbfile.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oa11m0ttknCPGxMJ357
            client-secret: TGnynQFF8F5ePXyTfDd9ZN_eCgBIILACngE4-Q3H
